### ISSUE TITLE
arbitary rotation000 merge with no and other solution types present.

### ISSUE THREAD

**Issue by rvweeren** [jurjen93/lofar_helpers#27]
https://github.com/jurjen93/lofar_helpers/blob/6c1ccfe561d782eab4a6e121e919a1657ae01f0d/h5_merger.py#L2575

If there are no amplitude000/phase000 present the merge will fail(?). It would be good if we also have the ability to merge a rotation000 only h5. In addition, a recent DP3 update has also allowed new solution types. So rotation+scalarphase rotation+phaseonly, rotatation+scalaramplitide, rotation+amplitudeonly, rotation+scalarcomplexgain are also possibilities. In other words, rotation000+amplitude000 or rotation000+phase000 also exist now. (both the diagonal and scalar variants of amplitude000 and phase000).

**Comment by jurjen93** [comment]
Added updates to the split_direction function, ensuring that it takes into account if an input file has or does not have amp/phase.

**Comment by rvweeren** [comment]
I now get this error (seems a polarization axis is expected, note that phase000 and amplitude000 can occur both with and without pol-axis. In this case, I did a rotation+scalarphase so no pol-axis)

(h5 for testing purposes are here /data1/rvweeren/Perseus_LBA_run1/experiment_withnew_rotations/tmph5/)

```
##################################
START MERGE HDF5 TABLES FOR LOFAR
##################################

Merging the following tables:
scalarphase2_skyselfcalcyle000_Perseus_run1.ms.copy.avg.h5
scalarphase1_skyselfcalcyle000_Perseus_run1.ms.copy.avg.h5
rotation+scalarphase0_skyselfcalcyle000_Perseus_run1.ms.copy.avg.h5

Rotation table in rotation+scalarphase0_skyselfcalcyle000_Perseus_run1.ms.copy.avg.h5 splitting table into fulljones for correct merging
Traceback (most recent call last):
  File "/net/rijn/data2/rvweeren/LoTSS_ClusterCAL/facetselfcal.py", line 10376, in <module>
    main()
  File "/net/rijn/data2/rvweeren/LoTSS_ClusterCAL/facetselfcal.py", line 10102, in main
    wsclean_h5list = calibrateandapplycal(mslist, i, args, solint_list, nchan_list, args['soltype_list'], \
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/net/rijn/data2/rvweeren/LoTSS_ClusterCAL/facetselfcal.py", line 8208, in calibrateandapplycal
    h5_merger.merge_h5(h5_out=parmdbmergename,h5_tables=parmdbmergelist[msnumber][::-1],ms_files=ms,\
  File "/net/rijn/data2/rvweeren/LoTSS_ClusterCAL/h5_merger.py", line 2878, in merge_h5
    rot_h5, phaseamp_h5 = split_rotation(h5_in)
                          ^^^^^^^^^^^^^^^^^^^^^
  File "/net/rijn/data2/rvweeren/LoTSS_ClusterCAL/h5_merger.py", line 2584, in split_rotation
    H.remove_node("/sol000/phase000", "pol", recursive=True)
  File "/opt/lofar/pyenv-py3/lib64/python3.11/site-packages/tables/file.py", line 1761, in remove_node
    obj = self.get_node(where, name=name)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/lofar/pyenv-py3/lib64/python3.11/site-packages/tables/file.py", line 1603, in get_node
    node = self._get_node(nodepath)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/lofar/pyenv-py3/lib64/python3.11/site-packages/tables/file.py", line 1550, in _get_node
    node = self._node_manager.get_node(nodepath)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/lofar/pyenv-py3/lib64/python3.11/site-packages/tables/file.py", line 411, in get_node
    node = self.node_factory(key)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/lofar/pyenv-py3/lib64/python3.11/site-packages/tables/group.py", line 1137, in _g_load_child
    node_type = self._g_check_has_child(childname)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/lofar/pyenv-py3/lib64/python3.11/site-packages/tables/group.py", line 375, in _g_check_has_child
    raise NoSuchNodeError(
tables.exceptions.NoSuchNodeError: group ``/`` does not have a child named ``/sol000/phase000/pol``
(pyenv-py3) 

```

**Comment by jurjen93** [comment]
resolved with try-except statements
